$ANSIBLE_VAULT;1.1;AES256
38346434613965326432313539333962313331313735323866643731663638353161613831633230
3134316462313532353136613162613862393165313238320a663535623633663664386634303836
30336135666337393032353734313337333936316565633936633032636230643831333230316331
6563336236616462310a653865343832623732383665396564326635626234616462613835633430
35623034613264393261333163663234623838313862366337373662376464343339383032666232
34343539663431643661616461633233633762393664666339386537326431623265653235343233
30616564363463303562343733343062343266636530623234323064316466646665333663366462
64623066323939316531353866333464306631383530353866623561383262326464353939316466
32323833653764326133313936376164666637353736396263333838616636613166363434356661
35623930656535346635336237393538623466343636303738353532386430646233643337366261
626661623064313161383136613963303361
