# ansible/group_vars/dev_vm.yml
---
# Local source directory where the Ansible playbook is run from
main_repo_source_dir: "/home/hunter/IdeaProjects/home-network-guardian"

# Base directory on the remote host (VM) for deployment
remote_deploy_base: "/home/hunter"

# The user used for deployment
deployment_user: "{{ ansible_user }}"