# ansible/group_vars/home_guardian_servers.yml
---
# Local source directory where the Ansible playbook is run from
main_repo_source_dir: "/home/hunter/IdeaProjects/home-network-guardian"
# Base directory on the remote host for temporary file copies (Portainer, etc.)
remote_deploy_base: "/home/hunter"
# The user used for deployment
deployment_user: "{{ ansible_user }}"
