version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.111.0
    container_name: n8n-server
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    user: "${UID}:${GID}"
    environment:
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=Europe/Warsaw
      - TZ=Europe/Warsaw
    restart: unless-stopped

volumes:
  n8n_data:
    driver: local